version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    networks:
      - ecommerce
      - authnetwork
  authdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    #volumes:
    #   - ./auth/mongodb:/data/db
    networks: 
      - authnetwork

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - ecommerce
      
  order:
    build: ./order
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./order/.env
    networks:
      - ecommerce
      - ordernetwork

  orderdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # ports:
    #  - 27018:27017
    # volumes:
    #   - ./order/mongodb:/data/db
    networks:
      - ordernetwork

  product:
    build: ./product
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./product/.env
    networks:
      - ecommerce
      - productnetwork

  productdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27019:27017
    # volumes:
    #   - ./product/mongodb:/data/db
    networks:
      - productnetwork

  api-gateway:
    build: ./api_gateway
    ports:
      - "3003:3003"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - ecommerce
      - gatewaynetwork
  
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./api_gateway/redis/root:/root/redis 
      - ./api_gateway/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment: 
      - REDIS_PASSWORD=redis-pass-key
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
    networks: 
      - gatewaynetwork
    

networks:
  ecommerce:
  authnetwork:
  productnetwork:
  ordernetwork:
  gatewaynetwork: