// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhq7BXy88_PBA-M80puNXRHYNtIKL75sQ',
    appId: '1:168268340809:web:ac7cc52652e3cfdca52998',
    messagingSenderId: '168268340809',
    projectId: 'ecommerce-414913',
    authDomain: 'ecommerce-414913.firebaseapp.com',
    storageBucket: 'ecommerce-414913.appspot.com',
    measurementId: 'G-H68M6FNH03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTX08zjxtdHuuYqKkGubHnV-Byof2ZsRE',
    appId: '1:168268340809:android:4205bcf32f21bac4a52998',
    messagingSenderId: '168268340809',
    projectId: 'ecommerce-414913',
    storageBucket: 'ecommerce-414913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT9q6F7GiA79yJdkczJVkn-uNbkuVYCpI',
    appId: '1:168268340809:ios:52009343afc1c6c7a52998',
    messagingSenderId: '168268340809',
    projectId: 'ecommerce-414913',
    storageBucket: 'ecommerce-414913.appspot.com',
    androidClientId: '168268340809-f3mrh1qp6tr30bkvn2lmk156rgprg8kc.apps.googleusercontent.com',
    iosClientId: '168268340809-1nf9pu65sc2pqbiou4stkcpdo6el20kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
